import { HashRouter as Router, Routes, Route } from 'react-router-dom'
import { useState } from 'react'
import Navigation from './components/Navigation'
import Footer from './components/Footer'
import Home from './pages/Home'
import ToolsResources from './pages/ToolsResources'
import MortgageRates from './pages/MortgageRates'
import Glossary from './pages/Glossary'

import './App.css'

function App() {
  const [glossaryTerms] = useState({
    '1% Rule': 'A real estate investment guideline suggesting monthly rent should be at least 1% of the purchase price.',
    'Adjustable-Rate Mortgage (ARM)': 'A mortgage with a low introductory rate for a set period (e.g., 5 or 7 years), after which the rate adjusts based on market conditions.',
    'Amortization': 'The process of paying off a debt over time through regular payments that include both principal and interest.',
    'Appraisal': 'An expert assessment of a home\'s market value, required by the lender to ensure they aren\'t loaning more than the property is worth.',
    'Appreciation': 'The increase in a property\'s value over time. While not guaranteed, historically US real estate has appreciated.',
    'Cap Rate': 'Capitalization rate - A metric used to evaluate real estate investments, calculated as Net Operating Income divided by property value.',
    'Cash Flow': 'The net amount of cash generated by a rental property after all expenses are paid.',
    'Closing Costs': 'Fees paid at the end of the home-buying process, typically 2-5% of the home\'s price, including origination fees, appraisal, and title insurance.',
    'Credit Score': 'A number between 300-850 representing creditworthiness, used by lenders to determine risk and interest rates.',
    'Down Payment': 'The initial, upfront portion of the purchase price paid in cash. Can range from 3.5% (FHA) to 20% or more.',
    'Equity': 'The difference between the home\'s market value and the outstanding mortgage balance. The portion you actually "own."',
    'FHA Loan': 'A mortgage insured by the Federal Housing Administration, popular with first-time buyers, allowing down payments as low as 3.5%.',
    'Fixed-Rate Mortgage': 'A loan where the interest rate stays the same for the entire term, providing predictable monthly payments.',
    'Interest Rate': 'The percentage charged by a lender for borrowing money, significantly affecting total loan cost.',
    'Mortgage': 'A loan used to purchase real estate, where the property serves as collateral for the debt.',
    'PITI': 'Principal, Interest, Taxes, and Insurance - The four components of a total monthly mortgage payment.',
    'PMI': 'Private Mortgage Insurance - Required on conventional loans with less than 20% down payment to protect the lender.',
    'Pre-Approval': 'A conditional commitment from a lender for a specific loan amount based on verified financial information.',
    'REIT': 'Real Estate Investment Trust - A company that owns, operates, or finances income-generating real estate and trades like a stock.',
    'ROI': 'Return on Investment - A measure of investment efficiency, calculated as gain divided by cost, expressed as a percentage.'
  })

  return (
    <Router>
      <div className="min-h-screen bg-background">
        <Navigation />
        <main>
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/tools" element={<ToolsResources />} />
            <Route path="/mortgage-rates" element={<MortgageRates />} />
            <Route path="/glossary" element={<Glossary glossaryTerms={glossaryTerms} />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </Router>
  )
}

export default App

