import { HashRouter as Router, Routes, Route } from 'react-router-dom'
import { useState } from 'react'
import Navigation from './components/Navigation'
import Footer from './components/Footer'
import Home from './pages/Home'

// Tools & Calculators
import ToolsResources from './pages/ToolsResources'
import MortgageCalculator from './pages/tools/MortgageCalculator'
import AffordabilityCalculator from './pages/tools/AffordabilityCalculator'
import PropertyComparison from './pages/tools/PropertyComparison'
import InvestmentAnalysis from './pages/tools/InvestmentAnalysis'

import MortgageRates from './pages/MortgageRates'
import Glossary from './pages/Glossary'

// News & Analysis
import NewsHub from './pages/news/NewsHub'
import InvestorHoldingsSurge from './pages/news/InvestorHoldingsSurge'
import MortgageRatesHold from './pages/news/MortgageRatesHold'
import BuildToRentGrowth from './pages/news/BuildToRentGrowth'
import BrookfieldMegaDeals from './pages/news/BrookfieldMegaDeals'
import AccidentalLandlords from './pages/news/AccidentalLandlords'
import TinyHomesFinancing from './pages/news/TinyHomesFinancing'
import LandBankingStrategy from './pages/news/LandBankingStrategy'
import HousingStartsDecline from './pages/news/HousingStartsDecline'
import MortgageRateMagic from './pages/news/MortgageRateMagic'

// Institutional Players
import InstitutionalPlayers from './pages/InstitutionalPlayers'
import AmherstHoldings from './pages/institutional-players/AmherstHoldings'
import TriconResidential from './pages/institutional-players/TriconResidential'

// Markets
import LocalMarkets from './pages/markets/LocalMarkets'
import AustinTX from './pages/markets/AustinTX'
import DallasTX from './pages/markets/DallasTX'
import MiamiFL from './pages/markets/MiamiFL'

import './App.css'

function App() {
  const [glossaryTerms] = useState({
    '1% Rule': 'A real estate investment guideline suggesting monthly rent should be at least 1% of the purchase price.',
    'Adjustable-Rate Mortgage (ARM)': 'A mortgage with a low introductory rate for a set period (e.g., 5 or 7 years), after which the rate adjusts based on market conditions.',
    'AMH Development Program': 'American Homes 4 Rent\'s build-to-rent strategy where they acquire land and develop entire communities specifically for rental operations.',
    'Amortization': 'The process of paying off a debt over time through regular payments that include both principal and interest.',
    'Appraisal': 'An expert assessment of a home\'s market value, required by the lender to ensure they aren\'t loaning more than the property is worth.',
    'Appreciation': 'The increase in a property\'s value over time. While not guaranteed, historically US real estate has appreciated.',
    'Assets Under Management (AUM)': 'The total market value of investments that a financial institution or investment company manages on behalf of clients.',
    'BRRRR': 'Buy, Rehab, Rent, Refinance, Repeat - A real estate investment strategy for building a rental portfolio by forcing appreciation through renovations.',
    'Build-to-Rent (BTR)': 'A development strategy where homes are constructed specifically to be operated as rentals rather than sold to individual buyers.',
    'Buyer\'s Agent': 'A real estate agent who represents the buyer in a transaction, helping find homes, make offers, and navigate the process.',
    'Cap Rate': 'Capitalization rate - A metric used to evaluate real estate investments, calculated as Net Operating Income divided by property value.',
    'Cash Flow': 'The net amount of cash generated by a rental property after all expenses are paid.',
    'Cash-on-Cash Return': 'A rate of return that calculates the cash income earned on the cash invested in a property, expressed as a percentage.',
    'Cerberus Capital Management': 'A global private equity firm and the parent company of FirstKey Homes, providing capital for single-family rental investments.',
    'Closing Costs': 'Fees paid at the end of the home-buying process, typically 2-5% of the home\'s price, including origination fees, appraisal, and title insurance.',
    'Condo': 'A type of ownership where you own the individual unit but share ownership and costs for common areas through a Homeowners Association.',
    'Contingencies': 'Conditions in an offer that must be met for the sale to go through (e.g., satisfactory home inspection). Safety clauses for the buyer.',
    'Core FFO': 'Core Funds From Operations - A key metric for REITs that measures operating performance by excluding certain one-time items.',
    'Credit Score': 'A number between 300-850 representing creditworthiness, used by lenders to determine risk and interest rates.',
    'Days on Market': 'The number of days a property has been listed for sale, indicating market demand and pricing competitiveness.',
    'DCF': 'Discounted Cash Flow - A valuation method that estimates the value of an investment based on its expected future cash flows.',
    'Debt Service': 'The cash required to cover the repayment of interest and principal on a debt for a particular period.',
    'Debt-to-Income (DTI) Ratio': 'A percentage comparing total monthly debt payments to gross monthly income, used by lenders to assess affordability.',
    'Down Payment': 'The initial, upfront portion of the purchase price paid in cash. Can range from 3.5% (FHA) to 20% or more.',
    'Due Diligence': 'The investigation period where buyers conduct inspections and verify property conditions before finalizing the purchase.',
    'Earnest Money': 'A deposit made by a buyer to show serious intent to purchase. Held in escrow and applied toward the down payment at closing.',
    'Equity': 'The difference between the home\'s market value and the outstanding mortgage balance. The portion you actually "own."',
    'Escrow': 'A neutral third-party account that holds money and documents safely during the buying process until all conditions are met.',
    'FHA Loan': 'A mortgage insured by the Federal Housing Administration, popular with first-time buyers, allowing down payments as low as 3.5%.',
    'FICO Score': 'The most common type of credit score in the US, ranging from 300-850, used by lenders to assess creditworthiness.',
    'Fixed-Rate Mortgage': 'A loan where the interest rate stays the same for the entire term, providing predictable monthly payments.',
    'Gross Rental Income': 'The total rental income collected from a property before any expenses are deducted.',
    'HELOC': 'Home Equity Line of Credit - A revolving credit line secured by your home\'s equity, functioning like a credit card.',
    'Home Equity Loan': 'A fixed-amount loan secured by your home\'s equity, also called a second mortgage, with predictable payments.',
    'Home Inspector': 'An expert hired to thoroughly examine a home\'s condition (roof, plumbing, electrical, foundation) to identify potential problems.',
    'Homeowners Association (HOA)': 'An organization in condos or planned communities that makes and enforces rules for properties and residents.',
    'House Hacking': 'Living in a multi-unit property while renting out other units to offset housing costs.',
    'iBuyer': 'A company that uses technology to make instant offers on homes, such as Opendoor or Offerpad.',
    'Institutional Investor': 'Large-scale investors such as pension funds, insurance companies, or investment firms that purchase real estate as an asset class.',
    'Interest Rate': 'The percentage charged by a lender for borrowing money, significantly affecting total loan cost.',
    'IPO': 'Initial Public Offering - When a private company first sells shares to the public and becomes publicly traded.',
    'IRR': 'Internal Rate of Return - A metric used to evaluate the profitability of investments, expressed as an annual percentage.',
    'Joint Venture (JV)': 'A business arrangement where two or more parties pool resources for a specific real estate project or investment.',
    'Lender': 'The bank, credit union, or financial institution that provides the mortgage loan to purchase a home.',
    'Leverage': 'Using borrowed money to increase the potential return on an investment, common in real estate through mortgages.',
    'Main Street Renewal': 'Amherst Holdings\' property management arm that operates single-family rental homes across multiple markets.',
    'Market Capitalization': 'The total market value of a publicly traded company\'s outstanding shares.',
    'Median Sale Price': 'The middle price point of all homes sold in a market, with half selling above and half below this price.',
    'MLS': 'Multiple Listing Service - A database used by real estate professionals to share information about properties for sale.',
    'Months of Supply': 'A measure of housing inventory representing how long it would take to sell all available homes at the current sales pace.',
    'Mortgage': 'A loan used to purchase real estate, where the property serves as collateral for the debt.',
    'Net Operating Income (NOI)': 'Total rental income minus operating expenses, used in investment property analysis and cap rate calculations.',
    'Occupancy Rate': 'The percentage of rental units that are occupied by paying tenants at a given time.',
    'Off-Site Construction': 'Building components or entire structures in a factory setting before transporting to the final location.',
    'Panelized Components': 'Pre-manufactured building sections created in a factory for faster on-site assembly.',
    'PITI': 'Principal, Interest, Taxes, and Insurance - The four components of a total monthly mortgage payment.',
    'PMI': 'Private Mortgage Insurance - Required on conventional loans with less than 20% down payment to protect the lender.',
    'Portfolio Company': 'A company owned by a private equity firm or investment fund as part of their investment portfolio.',
    'Pre-Approval': 'A conditional commitment from a lender for a specific loan amount based on verified financial information.',
    'Pre-Qualification': 'A quick, informal estimate of borrowing capacity based on self-reported information, not a lender commitment.',
    'Pretium Partners': 'A private investment firm and the parent company of Progress Residential, specializing in residential real estate.',
    'Price per Square Foot': 'A metric calculated by dividing the property price by its square footage, used for comparing property values.',
    'Principal': 'The portion of a mortgage payment that reduces the loan balance, building equity in the property.',
    'ProCare': 'Invitation Homes\' branded property management service promising proactive maintenance and professional support.',
    'Property Management': 'The operation, control, and oversight of real estate, including tenant relations, maintenance, and rent collection.',
    'REIT': 'Real Estate Investment Trust - A company that owns, operates, or finances income-generating real estate and trades like a stock.',
    'Refinancing': 'Replacing an existing mortgage with a new loan, typically to get better terms, lower rates, or access equity.',
    'Renovation ROI': 'Return on Investment for home improvements, measuring how much value is added relative to the cost of renovations.',
    'Renters-by-Choice': 'Individuals or families who choose to rent rather than buy, often for lifestyle flexibility or financial reasons.',
    'ROI': 'Return on Investment - A measure of investment efficiency, calculated as gain divided by cost, expressed as a percentage.',
    'Sale-to-List Price Ratio': 'The percentage comparing the final sale price to the original listing price, indicating market strength.',
    'Same-Home NOI Growth': 'A metric measuring the year-over-year change in net operating income for properties owned for the full comparison period.',
    'School Ratings': 'Numerical scores (typically 1-10) that evaluate the quality of local schools, often from sources like GreatSchools.org.',
    'Securitization': 'The process of pooling various types of debt and selling them as bonds to investors.',
    'SFR': 'Single-Family Rental - The business of owning and renting detached single-family homes as an investment strategy.',
    'Single-Family Home (SFH)': 'A standalone, detached house on its own land where the owner is responsible for the entire property.',
    'StudioBuilt': 'Amherst Holdings\' factory in Texas that manufactures panelized components for single-family homes.',
    'Sun Belt': 'The southern and southwestern regions of the United States, known for warm climate and population growth.',
    'Title': 'A legal document that proves ownership of a property and the right to use, control, and dispose of it.',
    'Title Insurance': 'Insurance that protects against financial loss from defects in title to real property.',
    'Townhouse': 'A type of housing where you own your unit and land but share walls with neighbors, typically responsible for exterior maintenance.',
    'Transit Score': 'A 0-100 rating measuring how well a location is served by public transportation.',
    'Underwriting': 'The process by which lenders evaluate the risk of lending money for a mortgage based on credit, income, and property value.',
    'USDA Loan': 'A government-backed loan for buying homes in designated rural or suburban areas, often requiring no down payment.',
    'VA Loan': 'A mortgage loan guaranteed by the U.S. Department of Veterans Affairs, available to eligible veterans and service members.',
    'Vacancy Rate': 'The percentage of time a rental property sits empty between tenants, typically budgeted at 5-10%.',
    'Vertical Integration': 'A business strategy where a company controls multiple stages of production or distribution, from acquisition to management.',
    'Walk Score': 'A 0-100 rating measuring how walkable a location is, with higher scores indicating more amenities within walking distance.'
  })

  return (
    <Router>
      <div className="min-h-screen bg-background">
        <Navigation />
        <main>
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/tools" element={<ToolsResources />} />
            <Route path="/tools/mortgage-calculator" element={<MortgageCalculator />} />
            <Route path="/tools/affordability-calculator" element={<AffordabilityCalculator />} />
            <Route path="/tools/property-comparison" element={<PropertyComparison />} />
            <Route path="/tools/investment-analysis" element={<InvestmentAnalysis />} />
            <Route path="/mortgage-rates" element={<MortgageRates />} />
            <Route path="/glossary" element={<Glossary glossaryTerms={glossaryTerms} />} />
            
            {/* News & Analysis */}
            <Route path="/news" element={<NewsHub />} />
            <Route path="/news/investor-holdings-surge" element={<InvestorHoldingsSurge />} />
            <Route path="/news/mortgage-rates-hold" element={<MortgageRatesHold />} />
            <Route path="/news/build-to-rent-growth" element={<BuildToRentGrowth />} />
            <Route path="/news/brookfield-mega-deals" element={<BrookfieldMegaDeals />} />
            <Route path="/news/accidental-landlords" element={<AccidentalLandlords />} />
            <Route path="/news/tiny-homes-financing" element={<TinyHomesFinancing />} />
            <Route path="/news/land-banking-strategy" element={<LandBankingStrategy />} />
            <Route path="/news/housing-starts-decline" element={<HousingStartsDecline />} />
            <Route path="/news/mortgage-rate-magic" element={<MortgageRateMagic />} />

            {/* Institutional Players */}
            <Route path="/institutional-players" element={<InstitutionalPlayers />} />
            <Route path="/institutional-players/amherst-holdings" element={<AmherstHoldings />} />
            <Route path="/institutional-players/tricon-residential" element={<TriconResidential />} />

            {/* Markets */}
            <Route path="/markets" element={<LocalMarkets />} />
            <Route path="/markets/austin-tx" element={<AustinTX />} />
            <Route path="/markets/dallas-tx" element={<DallasTX />} />
            <Route path="/markets/miami-fl" element={<MiamiFL />} />
          </Routes>
        </main>
        <Footer />
      </div>
    </Router>
  )
}

export default App
